version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: swifttrade_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-swifttrade}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-swifttrade}"]
      interval: 5s
      timeout: 5s
      retries: 12

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: swifttrade_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@db:5432/swifttrade}
      - ENV=${ENV:-dev}
      - UVICORN_RELOAD=
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw

volumes:
  db_data:
